# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_PATH: ${{github.workspace}}/artifacts

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: create artifacts dir
        run: |
          echo ARTIFACTS_PATH: ${ARTIFACTS_PATH}
          ARTIFACTS_PATH=${HOME}/artifacts
          echo ARTIFACTS_PATH: ${ARTIFACTS_PATH}
          echo "ARTIFACTS_PATH=${ARTIFACTS_PATH}" >> ${GITHUB_ENV}
          mkdir -p ${ARTIFACTS_PATH}/logs

      - name: Run a multi-line script
        run: |
          env | sort
          echo HOME: ${HOME}
          echo ARTIFACTS_PATH: ${ARTIFACTS_PATH}
          echo Hello, world! | tee ${ARTIFACTS_PATH}/logs/run.log
          ls -lR ${ARTIFACTS_PATH}
          mkdir reports
          echo Add other actions to build, > reports/out
          echo test, and deploy your project. > reports/out

      - name: collect artifacts
        run: |
          mv reports ${ARTIFACTS_PATH}
          ls -lR ${ARTIFACTS_PATH}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: report-and-logs
          path: ${{env.ARTIFACTS_PATH}}
